# fly.toml file generated for remix-app-jokes on 2023-09-19T10:31:43-07:00

app = "remix-app-jokes"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
